pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
    tool name: 'gradle-4.7', type: 'gradle'
        stage('Build') {
            steps {
                sh 'gradle assemble'
            }
        }
         stage('Test') {
            steps {
                sh 'gradle test'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'gradle docker'
            }
        }
        stage('Run Docker Image') {
            steps {
                sh 'gradle dockerRun'
            }
        }
    }
}