pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
	    
        stage('Build') {
            steps {
                withGradle(gradle: "gradle-4.8",
           JDK: "jdk1.8",
           gradleProperties: "gradle.properties",
           gradleCacheDir: ".gradle/caches/") {
    sh "gradle build"
}
            }
        }
         stage('Test') {
            steps {
                sh './gradlew test'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh './gradlew docker'
            }
        }
        stage('Run Docker Image') {
            steps {
                sh './gradlew dockerRun'
            }
        }
    }
}