pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
    	
    	stage('Init'){
    	    steps{
    	        sh './BasicRestApplication/gradlew init' 
    	    }

    	}

	    
        stage('Build') {
            steps {
                
    			sh './BasicRestApplication/gradlew build'
            }
        }
    }
}